-- OBSOLETO — No ejecutar este archivo.
--
-- La tabla public.saldo_a_favor, sus indices, RLS y politicas
-- ahora estan definidos directamente en supabase/schema.sql.
--
-- Este archivo se conserva solo como referencia historica.
-- La migracion activa (columna socios.saldo_a_favor y RPC
-- registrar_pago_con_credito) tambien esta en schema.sql.
